CREATE TABLE "board" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "user_email" varchar NOT NULL,
  "status" varchar,
  "created_at" timestamp
);

CREATE TABLE "column" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "board_id" integer,
  "created_at" timestamp
);

CREATE TABLE "task" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" varchar,
  "title" varchar,
  "desc" varchar,
  "column_id" integer,
  "created_at" timestamp
);

CREATE TABLE "subtask" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_id" integer,
  "desc" varchar,
  "is_complete" boolean,
  "created_at" timestamp
);

CREATE INDEX ON "board" ("user_email");

CREATE INDEX ON "column" ("board_id");

ALTER TABLE "column" ADD FOREIGN KEY ("board_id") REFERENCES "board" ("id");

ALTER TABLE "task" ADD FOREIGN KEY ("column_id") REFERENCES "column" ("id");

ALTER TABLE "subtask" ADD FOREIGN KEY ("task_id") REFERENCES "task" ("id");
